[project]
name = "modernbert-mlx"
version = "0.1.0"
description = "Implementation of ModernBERT in MLX"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "datasets>=3.2.0",
    "huggingface-hub>=0.27.0",
    "mlx>=0.21.1",
    "pyyaml>=6.0.2",
    "transformers>=4.47.1",
]
